 ('Beijing','https://en.wikipedia.org/api/rest_v1/page/pdf/Beijing'),
 ('Tokyo','https://en.wikipedia.org/api/rest_v1/page/pdf/Tokyo'),
 ('Jakarta','https://en.wikipedia.org/api/rest_v1/page/pdf/Jakarta'),
 ('Delhi','https://en.wikipedia.org/api/rest_v1/page/pdf/New_Delhi'),
 ('Manila','https://en.wikipedia.org/api/rest_v1/page/pdf/Manila'),
 ('Dhaka','https://en.wikipedia.org/api/rest_v1/page/pdf/Dhaka'),
 ('Moscow','https://en.wikipedia.org/api/rest_v1/page/pdf/Moscow'),
 ('Karachi','https://en.wikipedia.org/api/rest_v1/page/pdf/Karachi'),
 ('Singapore','https://en.wikipedia.org/api/rest_v1/page/pdf/Singapore'),
 ('Tashkent','https://en.wikipedia.org/api/rest_v1/page/pdf/Tashkent'),
 ('Phnom Penh','https://en.wikipedia.org/api/rest_v1/page/pdf/Phnom_Penh'),
 ('Bishkek','https://en.wikipedia.org/api/rest_v1/page/pdf/Bishkek'),
 ('Tbilisi','https://en.wikipedia.org/api/rest_v1/page/pdf/Tbilisi'),
 ('Sri Jayewardenepura Kotte','https://en.wikipedia.org/api/rest_v1/page/pdf/Sri_Jayawardenepura_Kotte'),
 ('Ho Chi Minh City','https://en.wikipedia.org/api/rest_v1/page/pdf/Ho_Chi_Minh_City'),